# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0007_auto_20150921_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', mezzanine.core.fields.FileField(max_length=255)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('products', models.ManyToManyField(related_name='downloads', to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0, editable=False, verbose_name='Download Count')),
                ('download_limit', models.IntegerField(default=5, verbose_name='Download Limit')),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='shop.Order')),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='shop.Product')),
            ],
        ),
    ]
