# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge_downloads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='acquisition',
            name='download',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cartridge_downloads.Download'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cartridge_downloads.Transaction'),
            preserve_default=False,
        ),
    ]
