# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge_downloads', '0002_auto_20160829_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='download',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cartridge_downloads.Download'),
            preserve_default=False,
        ),
    ]
